version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

executors:
  default:
    docker:
      - image: circleci/golang:1.13

jobs:
  test:
    executor: default
    steps:
      - checkout

      - restore_cache: # restores saved cache if no changes are detected since last run
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      - run: # Build test without output
          name: "Test1. Compile"
          command: |
            go build -o /dev/null
      - run:
          name: "Test2. UnitTest"
          command: |
            mkdir -p reports/junit
            go get -u github.com/jstemmer/go-junit-report
            go test ./... -v 2>&1 | go-junit-report > reports/junit/report.xml
      - run:
          name: "Test3. Coverage"
          command: |
            mkdir -p reports/coverage
            go test ./... -race -covermode=atomic -coverprofile=reports/coverage/coverage.txt
      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - store_test_results:
          path: reports/junit/
      - store_artifacts:
          path: reports/junit/
      - codecov/upload: # upload code coverage result
          file: reports/coverage/*.txt

workflows:
  version: 2
  build-test-deploy:
    jobs:
      # test jobs
      - test:
          filters:
            tags:
              only: /.*/
